# !目前不支持热更新

# Tomcat相关配置
tomcat:
  #端口
  port: 8080
  #webapp目录
  webappDir: "Anykat-management/src/webapp"
  #扫描的目录
  classesDir: "Anykat-management/target/classes"


# Jwt相关配置
jwt:
  #Jwt密钥
  secretKey:  "ProjectAnykatKaCatIsMyLongLongSecretKeyTo256Bits"
  #管理员Jwt密钥
  adminSecretKey: "ProjectAnykatKaCatIsMyLongLongSecretKeyTo256BitsUsingByAdmin"
  #有效时间
  expireTime: 21600000 #  6h


# DI容器扫描的包
container:
  scanPackages:
    - "com.anyview.xiazihao.service"
    - "com.anyview.xiazihao.controller"
    - "com.anyview.xiazihao.dao"
    - "com.anyview.xiazihao.aspect"

# 数据库连接池相关设置
hakimi:
  url: "jdbc:mysql://localhost:3306/anykat"
  username: "root"
  password: "pin666"
  maxSize: 10
  minIdle: 5
  maxWaitMillis: 10000
  #触发扩容的等待线程阈值（建议=maxSize*0.3）
  maxWaitThreads: 3
  #空闲连接超时时间（默认30分钟）
  idleTimeoutMillis: 1800000