services:
  mysql:
    image: mysql:8
    container_name: mysql
    ports:
      - "3307:3306"
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: d1231sdagf21dw123
    volumes:
      - "/usr/local/app/mysql/conf:/etc/mysql/conf.d"
      - "/usr/local/app/mysql/data:/var/lib/mysql"
      - "/usr/local/app/mysql/init:/docker-entrypoint-initdb.d"
    networks:
      - anykat-net
  anykat:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: anykat-server
    ports:
      - "8080:8080"
    volumes:
      # 映射日志目录（宿主机目录:容器目录）
      - "/usr/local/app/anykat/logs:/anykat/logs"
      # 映射 webapp 静态资源目录
      - "/usr/local/app/anykat/webapp:/anykat/webapp"
      # 映射配置文件
      - "/usr/local/app/anykat/config.yml:/anykat/config.yml"
      # 映射 jar 包
      - "/usr/local/app/anykat/anykat.jar:/anykat/anykat.jar"
    networks:
      - anykat-net
    depends_on:
      - mysql
  nginx:
    image: nginx:1.20.2
    container_name: nginx-anykat
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/usr/local/app/nginx/conf/nginx.conf:/etc/nginx/nginx.conf"
      - "/usr/local/app/nginx/ssl:/etc/nginx/ssl"
      - "/usr/local/app/nginx/html:/usr/share/nginx/html"
      - "/usr/local/app/nginx/logs:/var/log/nginx"
    depends_on:
      - anykat
    networks:
      - anykat-net
networks: #指定网络
  anykat-net:
    name: katnet